---
- name: Set a hostname
  hostname:
    name: sabnzb

- name: Setup /etc/hosts file
  ansible.posix.synchronize:
    checksum: yes
    src: hosts
    dest: /etc/hosts
    owner: yes
    group: yes

- name: Create Media Group on all Media Servers
  group:
    name: media
    gid: 3000
    state: present
    system: yes

- name: Create OPT APPS directory on all Media Servers
  file:
    path: /opt/apps
    state: directory
    group: media
    owner: root
    mode: '770'

- name: Create the sabnzb user
  user:
    name: sabnzb
    home: /opt/apps/sabnzb
    create_home: yes
    move_home: yes
    password: "$6$13EsWp/t8Y4T0/xH$m2I7DWDjcodxFTHAZIad1lZSers0XREz1dHkHzckd5TLPxJ5Wipv32gD4236M2BSIc.SE/.6kEc89fyEj/e.00"
    group: media
    state: present

- name: Create OPT APPS MEDIA directory on all Media Servers
  file:
    path: /opt/apps/media
    state: directory
    group: media
    owner: root
    mode: '770'

- name: Mount NFS location on all Media Servers
  ansible.posix.mount:
    src: wickednas.snyderfamily.int:/plex
    path: /opt/apps/media
    fstype: nfs
    opts: defaults,rw
    state: mounted

- name: Install GIT
  dnf:
    name: git
    state: latest

- name: Install SabNZB Required Utilities
  vars:
    sab_tools:
      - par2cmdline
      - unrar
      - python3-cheetah
      - python3-feedparser
  dnf:
    name: "{{ sab_tools }}"
    state: latest

- name: Install SabNZB
  git:
    repo: https://github.com/sabnzbd/sabnzbd
    clone: yes
    dest: /opt/apps/sabnzb/.appdata
    version: master

- name: Install SabNZB Required Python Modules
  pip:
    requirements: /opt/apps/sabnzb/.appdata/requirements.txt
    state: present

- name: Update Ownership and Permissions
  file:
    path: /opt/apps/sabnzb/
    owner: sabnzb
    group: media
    mode: '0770'
    recurse: yes

- name: Copy systemd service file
  ansible.posix.synchronize:
    checksum: yes
    src: sabnzb.service
    dest: /etc/systemd/system/sabnzb.service
    owner: yes
    group: yes
  register: systemd

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: systemd.changed

- name: Enable and Start SabNZB
  systemd:
    name: sabnzb
    enabled: yes
    state: started

