---
- name: Set a hostname
  hostname:
    name: tautulli

- name: Setup /etc/hosts file
  ansible.posix.synchronize:
    checksum: yes
    src: hosts
    dest: /etc/hosts
    owner: yes
    group: yes

- name: Create Media Group on all Media Servers
  group:
    name: media
    gid: 3000
    state: present
    system: yes

- name: Create OPT APPS directory on all Media Servers
  file:
    path: /opt/apps
    state: directory
    group: media
    owner: root
    mode: '770'

- name: Create the tautulli user
  user:
    name: tautulli
    home: /opt/apps/tautulli
    create_home: yes
    move_home: yes
    password: "$6$13EsWp/t8Y4T0/xH$m2I7DWDjcodxFTHAZIad1lZSers0XREz1dHkHzckd5TLPxJ5Wipv32gD4236M2BSIc.SE/.6kEc89fyEj/e.00"
    group: media
    state: present

- name: Install Tautulli
  git:
    repo: https://github.com/Tautulli/Tautulli.git
    clone: yes
    dest: /opt/apps/tautulli

- name: Copy systemd service file
  ansible.posix.synchronize:
    checksum: yes
    src: tautulli.service
    dest: /lib/systemd/system/tautulli.service
    owner: yes
    group: yes
  register: systemd

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: systemd.changed

- name: Enable and Start Tautulli
  systemd:
    name: tautulli
    enabled: yes
    state: started