---
- name: Set a hostname
  hostname:
    name: tautulli

- name: Setup /etc/hosts file
  ansible.posix.synchronize:
    checksum: yes
    src: hosts
    dest: /etc/hosts
    owner: yes
    group: yes

- name: Install GIT
  dnf:
    name: git
    state: latest

- name: Install Tautulli
  git:
    repo: https://github.com/Tautulli/Tautulli.git
    clone: yes
    dest: /opt/apps/tautulli/.appdata

- name: Update Ownership and Permissions
  file:
    path: /opt/apps/tautulli
    owner: tautulli
    group: media
    mode: '0770'
    recurse: yes

- name: Copy systemd service file
  ansible.posix.synchronize:
    checksum: yes
    src: tautulli.service
    dest: /lib/systemd/system/tautulli.service
    owner: yes
    group: yes
  register: systemd

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: systemd.changed

- name: Enable and Start Tautulli
  systemd:
    name: tautulli
    enabled: yes
    state: started