---
- name: Set a hostname
  hostname:
    name: plex

- name: Setup /etc/hosts file
  ansible.posix.synchronize:
    checksum: yes
    src: hosts
    dest: /etc/hosts
    owner: yes
    group: yes

- name: Create Media Group on all Media Servers
  group:
    name: media
    gid: 3000
    state: present
    system: yes

- name: Create OPT APPS directory on all Media Servers
  file:
    path: /opt/apps
    state: directory
    group: media
    owner: root
    mode: '770'

- name: Create the Plex user
  user:
    name: plex
    home: /opt/apps/plex
    create_home: yes
    move_home: yes
    password: "$6$13EsWp/t8Y4T0/xH$m2I7DWDjcodxFTHAZIad1lZSers0XREz1dHkHzckd5TLPxJ5Wipv32gD4236M2BSIc.SE/.6kEc89fyEj/e.00"
    group: media
    state: present

- name: Create OPT APPS MEDIA directory on all Media Servers
  file:
    path: /opt/apps/media
    state: directory
    group: media
    owner: root
    mode: '770'

- name: Create OPT APPS PLEX APPDATA directory
  file:
    path: /opt/apps/plex/.appdata
    state: directory
    group: media
    owner: root
    mode: '770'

- name: Mount NFS location on Plex
  ansible.posix.mount:
    src: wickednas.snyderfamily.int:/plex
    path: /opt/apps/media
    fstype: nfs
    opts: defaults,rw
    state: mounted

- name: Mount Plex AppData
  ansible.posix.mount:
    src: wickednas.snyderfamily.int:/plex_appdata
    path: /opt/apps/plex/.appdata
    fstype: nfs
    opts: defaults,rw
    state: mounted

- name: Import the Plex Repo
  yum_repository:
    name: "PlexRepo"
    description: "Plex Media Server Linux Repository"
    baseurl: "https://downloads.plex.tv/repo/rpm/$basearch/"
    enabled: yes
    gpgkey: "https://downloads.plex.tv/plex-keys/PlexSign.key"
    gpgcheck: yes
    keepcache: "0"
    metadata_expire: "1"

- name: Install Plex
  dnf:
    name: plexmediaserver
    state: latest

- name: Create the plex override directory
  file:
    path: "/etc/systemd/system/plexmediaserver.service.d"
    state: directory
    owner: root
    group: media
    mode: '0770'

- name: Setup the Plex Override File
  ansible.posix.synchronize:
    checksum: yes
    src: override.conf
    dest: "/etc/systemd/system/plexmediaserver.service.d/override.conf"
    owner: yes
    group: yes
  register: override

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: override.changed

- name: Enable and Start Plex Media Server
  systemd:
    name: plexmediaserver
    enabled: yes
    state: started
